Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2020-11, with the labels that each got.

#219 Em 3090 spring boot upgrade
  .gitignore
  bin/start-local-environment.sh
  build.gradle
  charts/em-npa/Chart.yaml
  charts/em-npa/requirements.yaml
  charts/em-npa/values.yaml
  config/owasp/dependency-check-suppressions.xml
  dependency-check-suppressions.xml
  docker-compose-dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/DocumentTaskResourceIntTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-219

#257 Updated cnp-module-key-vault branch
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-npa-pr-257

#259 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-npa-pr-259

#258 EM-3238 -NPA API : Investigate NPA api failing nightly build jobs
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-258

#246 EM-3209 NPA: Update functional and smoke test cases to generate step …
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-npa-pr-246

#267 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-npa-pr-267

#268 Removed mi value for env tf files
  infrastructure/aat.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-npa-pr-268

#271 Updated em-test-helper version
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-271
