Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2020-12, with the labels that each got.

#279 EM-3260 - NPA API : Add retry logic for failing functional test cases
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
Labels: ns:em, prd:em, rel:em-npa-pr-279

#283 EM-3282 - NPA API - Suppress nightly jobs dependency vulnerability er…
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-283

#284 Resolved vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-284

#294 Resolved vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-294

#295 Resolved vulnerability
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-295
