Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2020-05, with the labels that each got.

#149 Em 2884 integrate pact test in pipeline
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
  pacts/npa_api-idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java
Labels: ns:em, rel:em-npa-pr-149

#150 Add debug logging for pact
  Jenkinsfile_CNP
Labels: ns:em, rel:em-npa-pr-150

#151 EM-2721 : Serenity Reporting for NPA
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
Labels: ns:em, rel:em-npa-pr-151

#153 EM-2721 : NPA Serenity Single page reports.
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, rel:em-npa-pr-153

#156 EM-2884 request body generation in pact json
  build.gradle
  dependency-check-suppressions.xml
  pacts/npa_api-idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java
Labels: ns:em, rel:em-npa-pr-156

#157 Reverted hibernate_sequence change
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
  src/main/resources/db/db.changelog-master.xml
Labels: ns:em, rel:em-npa-pr-157

#161 remove in cht
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:em, rel:em-npa-pr-161

#163 Update README to remove hmcts spring template content and update setup
  README.md
  dependency-check-suppressions.xml
Labels: ns:em, rel:em-npa-pr-163

#164 Add XUI to S2S whitelist
  src/main/resources/application.yaml
Labels: ns:em, rel:em-npa-pr-164

#166 Update Jenkinsfile for swagger
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
Labels: ns:em, rel:em-npa-pr-166

#167 EM-2976: Add library to fix issue with jbig2 images
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, rel:em-npa-pr-167

#168 Updated Swagger doc
  src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
Labels: ns:em, rel:em-npa-pr-168
