Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-07, with the labels that each got.

#553 fix mutation plugin
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-553

#559 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-559

#564 Removed binary url
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-564

#566 Added in fortify library
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  src/test/resources/logback.xml
Labels: ns:em, prd:em, rel:em-npa-pr-566

#567 Added in logging to capture the consuming service name
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspect.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/ServiceNameAspectTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-567

#574 Updated Chart Java version
  charts/em-npa/Chart.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-574
