Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-01, with the labels that each got.

#318 Resolved Vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-318

#320 Resolved Vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-320

#328 EM-3429 - EM-NPA: Failed to generate serenity report
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-328
