Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-02, with the labels that each got.

#335 Added in flux test var
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-335

#345 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-345

#346 Added postgres v11 details
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-346

#355 Updated postgres v11 details
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-npa-pr-355

#356 EM-3510- Check & Update PACT/Jupiter Unit tests related Dependencies
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-356

#357 EM-3519 - suppress security scan error
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-357

#369 Updated terraform and gradle version
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-npa-pr-369
