Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-08, with the labels that each got.

#586 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-586

#591 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-591

#608 Fix terraform version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-npa-pr-608
