Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-09, with the labels that each got.

#615 EM-4027-SecurityScanFix
  audit.json
  security.sh
Labels: ns:em, prd:em, EM-Automation, rel:em-npa-pr-615

#610 Added in toggle logic for documentTask endpoint
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/DocumentTaskScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/ToggleProperties.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/DocumentTaskResource.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-610

#622 EM-3982: Syncronise Demo/PerfTest/ITHC branches with master
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-npa-pr-622

#626 EM-4047-NightlyPipeline Fix
  audit.json
Labels: ns:em, prd:em, EM-Automation, rel:em-npa-pr-626

#628 terraform provider patch
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-npa-pr-628

#645 EM-4057-SecurityScan Fix
  audit.json
Labels: ns:em, prd:em, EM-Automation, rel:em-npa-pr-645

#646 Fixed checkstyle errors
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/npa/appinsights/AppInsightsEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SpringSecurityAuditorAware.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/RectangleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/EntityMapper.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/RectangleMapper.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImplTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-646

#648 EM-4057-Security Scan Fix
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-648
