Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-12, with the labels that each got.

#585 Added in CDAM changes
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  bin/idam-client-setup-roles.sh
  bin/start-local-environment.sh
  build.gradle
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/TestConfig.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/ToggleProperties.java
  src/aat/resources/adv_redaction_functional_tests_ccd_def.xlsx
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/CdamService.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/EmCaseDocumentClientApi.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/RedactionService.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/CdamServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImplTest.java
  src/test/resources/one-page.pdf
Labels: ns:em, prd:em, rel:em-npa-pr-585

#738 Fixed log4J vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-738

#739 Resolved vulnerability
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-npa-pr-739

#741 Updated log4j version
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-741

#742 Update fortifyscan
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:em, prd:em, rel:em-npa-pr-742
