Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2021-06, with the labels that each got.

#509 Fixed CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-509

#521 reverting dependabot changes
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-521

#503 Fixed Mass Assignment: Insecure Binder Configuration issue
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/npa/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/em/npa/info/BuildInfo.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/test/java/uk/gov/hmcts/reform/em/npa/info/BuildInfoTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-503

#544 reordering security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-npa-pr-544
