Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-03, with the labels that each got.

#804 update postgres version to 11 for local setup
  database/Dockerfile
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-npa-pr-804

#805 bump java chart
  charts/em-npa/Chart.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-805

#806 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-806

#812 Upgraded SpringBoot version to 2.6.4
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-812

#818 Fix security scan
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-818

#819 [EM-4310]-Native PDF Annotator Security Scan fix
  audit.json
Labels: ns:em, prd:em, EM-Automation, rel:em-npa-pr-819

#824 Updated column name to resolve reserve word issue
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/PersistentAuditEvent.java
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
Labels: ns:em, prd:em, rel:em-npa-pr-824

#825 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-825

#832 Fix CVE-2020-36518
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-832

#835 Remove jackson-bom
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-835

#837 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-npa-pr-837
