Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-06, with the labels that each got.

#909 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-909

#916 Exclude springboot-starter-security
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-916

#923 Updated local S2S & IDAM port
  bin/idam/idam.sh
  bin/start-local-environment.sh
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-923
