Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-04, with the labels that each got.

#842 Suppressed CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-842

#845 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-845

#850 EM-4389: Update the sonar exclusions
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/util/HeaderUtil.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-850
