Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-11, with the labels that each got.

#1142 EM-4744 avoid-CVE-2022-31692
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1142

#1161 EM-4813: Updated fileway core to 9.0.4
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1161

#1171 EM-4813: Updating flyway db to 9.8.2
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/npa/data/migration/FlywayNoOpStrategy.java
Labels: ns:em, prd:em, rel:em-npa-pr-1171

#1187 EM-4846 avoid vulnerability
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1187
