Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-09, with the labels that each got.

#1023 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1023

#1029 Added in dependabot config
  .github/dependabot.yml
  .github/renovate.json
  .github/stale.yml
  renovate.json
Labels: ns:em, prd:em, rel:em-npa-pr-1029

#1071 EM-4606 copy app-insight json
  Dockerfile
Labels: ns:em, prd:em, rel:em-npa-pr-1071

#1080 fix nightly build
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1080

#1081 EM-4607 vulnerability jettison
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1081
