Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-05, with the labels that each got.

#858 Ignore alerts
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-858

#881 Fixed build failure
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/RedactionScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-npa-pr-881

#860 Add ignores for 4 alerts relating to markups/?pageable=_GET
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-860

#882 Updated config for Renovate Bot
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-npa-pr-882

#883 [EM-4333]-Security Scan Fix
  audit.json
Labels: ns:em, prd:em, EM-Automation, rel:em-npa-pr-883

#892 Updated column size for principal
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
Labels: ns:em, prd:em, rel:em-npa-pr-892

#894 added further ignored stuff on to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-894

#899 Removed dependabot config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:em, prd:em, rel:em-npa-pr-899
