Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2022-02, with the labels that each got.

#793 Resolve CVE's
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-793

#794 Update helm chart
  charts/em-npa/Chart.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-794

#799 Fix CWE-862
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-799

#800 Removed suppressions
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-800
