Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-10, with the labels that each got.

#1681 Suppress CVE-2023-4586
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-1681

#1700 EM-5616 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-1700

#1698 EM-5505 reduce app-insight logs
  lib/applicationinsights.json
Labels: prd:em, ns:em, rel:em-npa-pr-1698

#1716 EM-5636 avoid vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-1716
