Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-09, with the labels that each got.

#1608 Resolve CVE-2023-41080
  build.gradle
Labels: prd:em, ns:em, rel:em-npa-pr-1608

#1607 Added in v14 db config for aat & prod
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: prd:em, add-or-update, ns:em, rel:em-npa-pr-1607

#1613 Updated default value for ENABLE_SEARCH_MARKUPS_ENDPOINT to true
  Jenkinsfile_CNP
  charts/em-npa/Chart.yaml
  charts/em-npa/values.preview.template.yaml
  charts/em-npa/values.yaml
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-npa-pr-1613

#1616 log format error
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
Labels: prd:em, ns:em, rel:em-npa-pr-1616

#1620 Reverted v14 DB changes
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: prd:em, destroy, ns:em, rel:em-npa-pr-1620

#1606 Updated User to refer from secret
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
Labels: prd:em, ns:em, rel:em-npa-pr-1606

#1638 Delete dependabot
  .github/dependabot.yml
  .github/stale.yml
Labels: prd:em, ns:em, rel:em-npa-pr-1638

#1639 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-npa-pr-1639

#1640 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-npa-pr-1640

#1649 EM-5569 Update dependency-check-suppressions.xml
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-1649
