Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-08, with the labels that each got.

#1574 em-5487: added 1 fingerprint to audit.json
  audit.json
Labels: prd:em, ns:em, rel:em-npa-pr-1574

#1580 Updated redaction logic
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
Labels: prd:em, ns:em, rel:em-npa-pr-1580

#1589 Added in v14 db config
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: prd:em, add-or-update, ns:em, rel:em-npa-pr-1589

#1595 Disable Demo branch sync
  Jenkinsfile_CNP
Labels: prd:em, ns:em, rel:em-npa-pr-1595

#1585 Added in index for 3 columns.
  src/main/resources/db/migration/V2__add_index_redid_docid_createdby.sql
  src/test/resources/config/application.yaml
Labels: prd:em, add-or-update, ns:em, rel:em-npa-pr-1585
