Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-12, with the labels that each got.

#1782 EM-5712 avoid CVE-2023-6378
  build.gradle
Labels: prd:em, ns:em, rel:em-npa-pr-1782

#1792 Updating NPA to remove entity value writes/db and batch configs
  build.gradle
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/npa/batch/EntityValueProcessor.java
  src/main/java/uk/gov/hmcts/reform/em/npa/batch/RemoveLargeObjectsTasklet.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/BatchConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriter.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V7_drop_entity_value_migrated.sql
  src/main/resources/db/migration/V8_drop_batch_tables.sql
Labels: prd:em, ns:em, rel:em-npa-pr-1792

#1799 Em 5213 new pact
  Jenkinsfile_CNP
  src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java
Labels: prd:em, ns:em, rel:em-npa-pr-1799

#1801 EM-5717 arrange dependency management
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-1801

#1796 Recreate user roles & access for Prod V15 DB
  infrastructure/main.tf
  infrastructure/prod.tfvars
Labels: prd:em, destroy, ns:em, rel:em-npa-pr-1796

#1808 Updated v15 DB default config
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
  infrastructure/main.tf
Labels: prd:em, add-or-update, ns:em, rel:em-npa-pr-1808

#1809 Em 5497 update v15 db config
  infrastructure/main.tf
Labels: prd:em, destroy, ns:em, rel:em-npa-pr-1809
