Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-06, with the labels that each got.

#1475 Updating renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-npa-pr-1475

#1443 Em-5116 spring-3 upgrade
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/EntityAuditEventListener.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/DocumentTask.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/PersistentAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/Rectangle.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/Redaction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslator.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/CdamService.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/CommentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RectangleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RedactionDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RedactionSetDTO.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/npa/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/npa/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorTestController.java
Labels: ns:em, prd:em, add-or-update, rel:em-npa-pr-1443

#1442 Em-5116 refactor serenity plugin
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1442

#1504 upgrade to gradle 8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
Labels: ns:em, prd:em, rel:em-npa-pr-1504

#1510 Updated CVE List
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-1510
