Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-05, with the labels that each got.

#1414 EM-5230 avoid CVE-2023-20862
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1414

#1421 EM-5253 checkstyle enable and fix
  build.gradle
  config/checkstyle/checkstyle.xml
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/npa/Application.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/HttpClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriter.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/AuditEventConverter.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/EntityAuditAction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/audit/EntityAuditEventListener.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/npa/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/npa/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/DocumentTask.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/PersistentAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/Rectangle.java
  src/main/java/uk/gov/hmcts/reform/em/npa/domain/Redaction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedaction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedaction.java
  src/main/java/uk/gov/hmcts/reform/em/npa/repository/CustomAuditEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/npa/repository/EntityAuditEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/npa/repository/MarkUpRepository.java
  src/main/java/uk/gov/hmcts/reform/em/npa/repository/PersistenceAuditEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/CustomParameterizedException.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslator.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/errors/package-info.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/util/PaginationUtil.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/MarkUpService.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/CommentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/IdamDetailsDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/external/annotation/RectangleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RectangleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RedactionDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RedactionSetDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImpl.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreUploaderImpl.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/EntityMapper.java
  src/test/java/uk/gov/hmcts/reform/em/npa/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/npa/config/HttpClientConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriterTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedactionTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/repository/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/TestUtil.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorTestController.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/FieldErrorVMTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreUploaderImplTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImplTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-1421

#1425 Refer to new AppInsights details
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-npa-pr-1425

#1432 EM-5116 bump spring cloud
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1432

#1431 EM-5116 remove unused class
  src/main/java/uk/gov/hmcts/reform/em/npa/service/EmCaseDocumentClientApi.java
Labels: ns:em, prd:em, rel:em-npa-pr-1431

#1434 Removed unused appinsights file
  infrastructure/application-insights.tf
Labels: ns:em, prd:em, destroy, rel:em-npa-pr-1434

#1433 Em-5116 arrange cloud libs
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/npa/smoke/SmokeTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-1433

#1435 bump serenity
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1435

#1439 Em-5116 remove javax libs and fix test
  build.gradle
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/errors/ExceptionTranslatorIntTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-1439

#1441 Em-5116 remove spring boot tests and refactor test
  src/test/java/uk/gov/hmcts/reform/em/npa/config/audit/AsyncEntityAuditEventWriterTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/redaction/ImageRedactionTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/redaction/PdfRedactionTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/DmStoreDownloaderImplTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-1441

#1457 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-npa-pr-1457

#1458 Updated service whitelist
  charts/em-npa/Chart.yaml
  charts/em-npa/values.yaml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-1458

#1466 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-npa-pr-1466
