Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-01, with the labels that each got.

#1232 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-1232

#1233 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-1233

#1237 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1237

#1263 EM-5015 bump hmcts.java
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-1263

#1267 EM-5019 fix-pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:em, prd:em, rel:em-npa-pr-1267
