Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2023-04, with the labels that each got.

#1376 Updated CVE List
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-npa-pr-1376

#1387 EM-5186 remove security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-npa-pr-1387

#1388 EM-5186 return json response
  src/aat/java/uk/gov/hmcts/reform/em/npa/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/WelcomeResource.java
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/WelcomeResourceTest.java
Labels: ns:em, prd:em, rel:em-npa-pr-1388

#1366 EM-5167 pr complete deployment
  charts/em-npa/Chart.yaml
  charts/em-npa/values.preview.template.yaml
  charts/em-npa/values.yaml
Labels: ns:em, prd:em, rel:em-npa-pr-1366

#1396 EM-5198 security scan
  audit.json
  functional-output/zap.reports
Labels: ns:em, prd:em, rel:em-npa-pr-1396

#1291 Create new endpoint to redact searched text
  Jenkinsfile_CNP
  charts/em-npa/Chart.yaml
  charts/em-npa/values.preview.template.yaml
  charts/em-npa/values.yaml
  src/aat/java/uk/gov/hmcts/reform/em/npa/functional/MarkUpScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/npa/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/MarkUpService.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/dto/redaction/RedactionSetDTO.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/mapper/EntityMapper.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/npa/rest/MarkUpResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/npa/service/impl/MarkUpServiceImplTest.java
Labels: ns:em, prd:em, add-or-update, rel:em-npa-pr-1291

#1398 EM-5198 suppress sec vul
  audit.json
Labels: ns:em, prd:em, rel:em-npa-pr-1398

#1405 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-npa-pr-1405
