Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2024-01, with the labels that each got.

#1824 Removed v11 DB related config
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: prd:em, destroy, ns:em, rel:em-npa-pr-1824

#1827 Updated flyway file names to be picked up by db migration stage
  src/main/resources/db/migration/V7__drop_entity_value_migrated.sql
  src/main/resources/db/migration/V8__drop_batch_tables.sql
Labels: prd:em, ns:em, rel:em-npa-pr-1827

#1830 use buildscript for flyway postgresql
  build.gradle
Labels: prd:em, ns:em, rel:em-npa-pr-1830

#1836 Em 5743 investigate redact issue
  src/main/java/uk/gov/hmcts/reform/em/npa/rest/RedactionResource.java
  src/main/java/uk/gov/hmcts/reform/em/npa/service/impl/RedactionServiceImpl.java
Labels: prd:em, ns:em, rel:em-npa-pr-1836

#1863 add graceful shutdown
  src/main/resources/application.yaml
Labels: prd:em, ns:em, no-changes, rel:em-npa-pr-1863

#1867 EM-5795 migrating to java 21
  build.gradle
Labels: prd:em, ns:em, rel:em-npa-pr-1867
