Repository hmcts/em-native-pdf-annotator-app, pull requests merged in 2024-07, with the labels that each got.

#2104 EM-6103 fix-check all vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-npa-pr-2104

#2114 revert-to fix master
  build.gradle
Labels: prd:em, ns:em, rel:em-npa-pr-2114

#2127 use dummy default key
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-npa-pr-2127

#2130 EM-5213 add pact provider test
  Jenkinsfile_CNP
  src/contractTest/java/uk/gov/hmcts/reform/em/npa/IdamConsumerTest.java
Labels: prd:em, ns:em, rel:em-npa-pr-2130

#2134 EM-5213 add pact provider test
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/em/npa/NpaPactProviderTest.java
Labels: prd:em, ns:em, rel:em-npa-pr-2134
